# Generated by Django 5.1.3 on 2024-12-29 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentlogin', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Books_data',
        ),
    ]
